site_name: DAO Ace Stream
theme:
  name: material
  custom_dir: templates
  palette:
    primary: blue grey
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    # - navigation.sections
    - navigation.tabs

extra:
  assets_root: "/assets"

extra_javascript:
  - assets/javascript/main.js

extra_css:
  - assets/css/colors.css
  - assets/css/popup.css
  - assets/css/buttons.css
  - assets/css/elements.css

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list
  - meta

plugins:
  - markdownextradata: {}
  - i18n:
      default_language: en
      languages:
        en: English
        ru: Русский
      nav_translations:
        ru:
          Overview: Обзор
          Products: Продукты
          Unexplored Internet: Интернет, о котором мало кто знает
          About the Project: О проекте
          Finances and Investment: Финансы и инвестиции
          Financial Services, DeFi: Инвестиционные программы, DeFi
          Crypto Assets of DAO Ace Stream: Криптоактивы DAO Ace Stream
          Token Classification, SEC: Классификация токенов, SEC
          Risk Assessment: Оценка рисков
          DMCA Compliance: Соответствие условиям DMCA
          The network that everyone needs!: Сеть, которая нужна всем!
          Foreword: Преамбула
          Network's Architecture: Архитектура Сети
          Performance Considerations: Производительность
          Security: Безопасность
          Traffic and time accounting: Учет трафика и времени
          System Tokens: Системные токены
          Token Exchange: Обмен токенов
          Traffic Payments: Расчеты за трафик
          Traffic Price: Цена трафика
          Payment for Traffic: Оплата трафика
          Credit Traffic: Кредитный трафик
          Traffic paid by Broadcasters: Оплата трафика бродкастерами
          Network's Participants: Участники Сети
          Broadcasters: Бродкастеры
          Copyright Holders: Правообладатели
          Distributors: Дистрибьюторы
          Oracles: Оракулы
          Services: Сервисы
          User's Channels: Пользовательские каналы
          Moderation: Система модерации
          List of Operations: Список операций
          Glossary: Словарь
          Accounts and Devices: Аккаунты и устройства
          Operations: Операции
          Fees: Комиссии
          Transport File: Транспортный файл
          Content Identifier: Идентификатор контента
          Traffic Unit: Единица трафика
          System Pools: Системные пулы
          Special Accounts: Специальные счета
          Geo Tag: Гео метка
          System Settings: Системные настройки
          System Smart Contracts: Системные смарт-контракты
          Ace Stream Foundation: Ace Stream Foundation
          Prediction Market: Рынок прогнозов
          Developers: Разработчикам
          Broadcasting: Бродкастерам
          Examples: Примеры
          Roadmap: Дорожная карта
          Home: На главную

nav:
  - Home: https://acestream.org/
  - About the Project:
    - Unexplored Internet: library/intro.md
    - DAO Ace Stream: library/dao-acestream.md
    - Finances and Investment:
      - Financial Services, DeFi: library/finances.md
      - Crypto Assets of DAO Ace Stream: library/crypto-assets-and-fees.md
      - Token Classification, SEC: system-tokens/token-classification.md
      - Risk Assessment: library/risk-assessment.md
    - The network that everyone needs!: library/usage.md
    - DMCA Compliance: library/dmca.md
    - Roadmap: roadmap/index.md
  - Ace Network:
    - Welcome: welcome.md
    - Get Started:
      - Intro: get-started/intro.md
      - Foreword: get-started/foreword.md
      - Ace Network Stack: get-started/ace-network-stack.md
      - Network's Architecture: get-started/network-architecture.md
      - Performance Considerations: get-started/performance.md
      - Security: get-started/security.md
      - Traffic and time accounting: get-started/traffic-time-accounting.md
    - System Tokens:
      - Overview: system-tokens/index.md
      - Ace Byte (XAB): system-tokens/ace-byte.md
      - Ace Asset (XAS): system-tokens/ace-asset.md
      - Ace Coin (XAC): system-tokens/ace-coin.md
      - Examples: system-tokens/examples.md
      - Token Exchange: system-tokens/exchange.md
    - Traffic Payments:
      - Traffic Price: traffic-payments/traffic-price.md
      - Payment for Traffic: traffic-payments/payments.md
      - Credit Traffic: traffic-payments/credit-trafic.md
      - Traffic paid by Broadcasters: traffic-payments/broadcaster-payments.md
    - Network's Participants:
      - Broadcasters: network-participants/broadcasters.md
      - Copyright Holders: network-participants/copyright-holders.md
      - Distributors: network-participants/distributors.md
      - Oracles: network-participants/oracles.md
    - Services:
      - Overview: services/index.md
      - Ace Deposit: services/ace-deposit.md
      - Ace Asset: services/ace-asset.md
      - Premium Pool: services/premium-pool.md
      - User's Channels: services/user-channels.md
      - Moderation: services/moderation.md
    - List of Operations:
      - Overview: list-of-operations/index.md
      - Ace Assets: list-of-operations/ace-asset.md
      - Ace Deposit: list-of-operations/ace-deposit.md
      - Distribute Subscriptions: list-of-operations/distribute-subscriptions.md
      - Inflation: list-of-operations/inflation.md
      - Purge Devices: list-of-operations/purge-devices.md
      - Purge Subscriptions: list-of-operations/purge-subscriptions.md
      - Reward Uploaders: list-of-operations/reward-uploaders.md
      - Add Device: list-of-operations/add-device.md
      - Buy Single Access: list-of-operations/buy-single-access.md
      - Buy Subscription: list-of-operations/buy-subscription.md
      - Create Premium Pool: list-of-operations/create-premium-pool.md
      - Remove Device: list-of-operations/remove-device.md
      - System Service Payment: list-of-operations/system-service-payment.md
      - User Service Payment: list-of-operations/user-service-payment.md
      - Non System Service Payment: list-of-operations/non-system-service-payment.md
      - Add Rights Holder: list-of-operations/add-rights-holder.md
      - Add Broadcasting Rights Contract: list-of-operations/add-broadcasting-rights-contract.md
      - Unlock System Tokens: list-of-operations/unlock-system-tokens.md
    - Software: software/index.md
    - NFT: nft/index.md
    - Prediction Market: prediction-market/index.md
    - Glossary:
      - Accounts and Devices: glossary/accounts-and-devices.md
      - Operations: glossary/operations.md
      - Fees: glossary/fees.md
      - Transport File: glossary/transport-file.md
      - Content Identifier: glossary/content-identifier.md
      - Traffic Unit: glossary/traffic-unit.md
      - System Pools: glossary/system-pools.md
      - Special Accounts: glossary/special-accounts.md
      - Geo Tag: glossary/geo-tag.md
      - System Settings: glossary/system-settings.md
      - System Smart Contracts: glossary/system-smart-contracts.md
      - Ace Stream Foundation: glossary/ace-stream-foundation.md
  - Broadcasting:
    - Intro: broadcasting/index.md
    - Get Started: broadcasting/get-started.md
    - Broadcasting Details:
      - MPEG TS: broadcasting/details/mpeg-ts.md
      - HLS: broadcasting/details/hls.md
    # - Broadcasting GUI: broadcasting/gui/index.md
    - Administration:
      - Configuring public and private nodes: broadcasting/administration/public-private-nodes.md
      - Node HTTP Interface: broadcasting/administration/node-http-interface.md
      # - Logging: broadcasting/administration/logging.md
      - Moving the source node: broadcasting/administration/moving-the-source-node.md
      # - Traffic Filtration: broadcasting/administration/traffic-filtration.md
    - Reference: broadcasting/reference.md
  - Developers:
    - Intro: developers/index.md
    - Connect to the Engine: developers/connect-to-engine.md
    - Start Playback: developers/start-playback.md
    - Search: developers/search.md
    # - Media Server: developers/media-server.md
    - Running the Engine:
      - Desktop: developers/running-engine-desktop.md
      - Android: developers/running-engine-android.md
      - Command Line Options: developers/engine-command-line-options.md
    - Knowledge Base:
      - List of Categories: developers/knowledge-base/list-of-categories.md
      # - "acestream: protocol": developers/acestream-protocol.md
      # - What is "Content ID" and "infohash"?: developers/content-id-and-infohash.md
    # - Utilities:
    #   - Content ID Generation: developers/utilities/content-id-generation.md
    - API Reference: developers/api-reference.md
    - Old Engine API (deprecated): developers/old-engine-api.md
  - Products: products/index.md
